LSI: false
safe: true
source: [your repo's top-level directory]
incremental: false
highlighter: rouge
gist:
  NoScript: false
cramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: Jekyll-theme-minimal
